FROM node:18-alpine
WORKDIR /app
COPY finalApp/frontend/package*.json ./
RUN npm install
COPY finalApp/frontend/ ./
EXPOSE 5173
ENV HOST=0.0.0.0
ENV PORT=5173
ENV NODE_ENV=development
ENV VITE_HOST=0.0.0.0
CMD ["sh", "-c", "npm run dev -- --host 0.0.0.0"] 